### ISSUE TITLE
ansible lint requiring galaxy namespace when run by molecule

### ISSUE THREAD

**Issue by PhilippSelenium** [ansible-community/molecule#3336] opened 2021-12-16 10:36 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible [core 2.12.1]
  config file = None
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = False
molecule 3.5.2 using python 3.8 
    ansible:2.12.1
    delegated:3.5.2 from molecule
    docker:1.0.2 from molecule_docker requiring collections: community.docker>=1.8.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

No errors when running `molecule lint`

# Actual Behaviour

running `molecule lint` throws:
```
DEBUG    Validating schema testrole/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, lint
INFO     Performing prerun...
INFO     Added ANSIBLE_LIBRARY=.cache/ansible-compat/c40683/modules:.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO     Added ANSIBLE_COLLECTIONS_PATH=.cache/ansible-compat/c40683/collections:.ansible/collections:/usr/share/ansible/collections
INFO     Added ANSIBLE_ROLES_PATH=.cache/ansible-compat/c40683/roles:.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
ERROR    Computed fully qualified role name of testrole does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

Traceback (most recent call last):
  File "bin/molecule", line 8, in <module>
    sys.exit(main())
  File "lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "lib/python3.8/site-packages/molecule/command/lint.py", line 120, in lint
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "lib/python3.8/site-packages/molecule/command/base.py", line 111, in execute_cmdline_scenarios
    scenario.config.runtime.prepare_environment()
  File "lib/python3.8/site-packages/ansible_compat/runtime.py", line 255, in prepare_environment
    self._install_galaxy_role(self.project_dir, ignore_errors=True)
  File "lib/python3.8/site-packages/ansible_compat/runtime.py", line 396, in _install_galaxy_role
    raise InvalidPrerequisiteError(msg)
ansible_compat.errors.InvalidPrerequisiteError: Computed fully qualified role name of testrole does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

```
But `ansible-lint .` runs without error

Adding a namespace to testrole/meta/main.yml 'fixes' the `molecule lint` command

# Steps to reproduce

Create empty role
```
molecule init role testrole --driver-name docker
```

content of testrole/.ansible-lint
```
skip_list:
  - meta-incorrect
  - meta-no-info
  - role-name
```

content of testrole/meta/main.yml
```
galaxy_info:
  #namespace: foo
  description: your role description
```

content of testrole/molecule/default/molecule.yml (same as default but added linter section)
```
dependency:
  name: galaxy
lint: |
  ansible-lint .
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
```

Execute
```
cd testrole
molecule lint  # --> error
ansible-lint .  # --> works
```

**Comment by mydoomfr** [comment] 2021-12-20 10:09
Facing to the same issue

maybe related to : https://github.com/ansible-community/ansible-compat/issues/78

**Comment by tadeboro** [comment] 2021-12-22 19:24
This bug is indeed a duplicate of https://github.com/ansible-community/ansible-compat/issues/78 The main problem is that Molecule uses the `ansible-compat` library for installing stuff and that helper is too sensitive when it comes to role metadata.

**Closed by tadeboro** 2021-12-22 19:24 UTC
Labels: bug

**Comment by RulerOf** [comment] 2022-10-17 05:35
Was this problem ever actually resolved?

```
╰─❯ molecule --version
molecule 4.0.2 using python 3.10
    ansible:2.13.5
    delegated:4.0.2 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

Still, attempting to run a molecule test tells me to go pound salt because it doesn't like my role name. Or the namespace. It doesn't _actually_ tell me what the problem is so I'm left guessing.

```
ERROR    Computed fully qualified role name of newrelic.newrelic-infra does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.
```

**Comment by zhan9san** [comment] 2022-10-17 13:30
@RulerOf 

Please refer to https://molecule.readthedocs.io/en/latest/configuration.html#role-name-check

It's better to discuss it in [discussions](https://github.com/ansible-community/molecule/discussions) next time.
