### ISSUE TITLE
Ansible's output is missing from molecule commands

### ISSUE THREAD

**Issue by gmolkvk** [ansible-community/molecule#3233] opened 2021-09-07 13:48 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible [core 2.11.4] 
  config file = None
  configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/redacted/kvk/vault/ansible/roles/test/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/redacted/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/redacted/kvk/vault/ansible/roles/test/venv/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
molecule 3.4.0 using python 3.8 
    ansible:2.11.4
    delegated:3.4.0 from molecule
```

Molecule installation method (one of):

- pip (venv)

```
python3 -m venv venv && source venv/bin/activate
pip install molecule==3.4.0
```

Ansible installation method (one of):

- pip

```
# above venv still activated
pip install ansible==4.4.0
```

Detail any linters or test runners used:

```
molecule init role test
cd test
molecule test
```

# Desired Behavior

```
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
WARNING  Failed to guess project directory using git: 
INFO     Guessed /moleculetest as project root directory
WARNING  Computed fully qualified role name of moleculetest does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

INFO     Using /home/runner/.cache/ansible-lint/4b824e/roles/moleculetest symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/runner/.cache/ansible-lint/4b824e/roles
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
INFO     Lint is disabled.
INFO     Running default > cleanup
WARNING  Skipping, cleanup playbook not configured.
INFO     Running default > destroy

PLAY [Destroy] *****************************************************************

TASK [Populate instance config] ************************************************
ok: [localhost]

TASK [Dump instance config] ****************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

INFO     Running default > syntax
# ... etcetera ...
```

# Actual Behaviour

Notice how everything after "INFO     Running default > destroy" is silent. The PLAY, TASK instructions are missing.

```
DEBUG    Validating schema /home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/molecule.yml.
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
WARNING  Failed to guess project directory using git: 
INFO     Guessed /home/redacted/kvk/vault/ansible/roles/test/test as project root directory
WARNING  Computed fully qualified role name of test does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

INFO     Using /home/redacted/.cache/ansible-lint/4165d8/roles/test symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/redacted/.cache/ansible-lint/4165d8/roles
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
INFO     Lint is disabled.
INFO     Running default > cleanup
WARNING  Skipping, cleanup playbook not configured.
INFO     Running default > destroy
DEBUG: ANSIBLE ENVIRONMENT:
ANSIBLE_COLLECTIONS_PATH: /home/redacted/.cache/molecule/test/default/collections:/home/redacted/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections
ANSIBLE_CONFIG: /home/redacted/.cache/molecule/test/default/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /home/redacted/kvk/vault/ansible/roles/test/venv/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/filter:/home/redacted/.cache/molecule/test/default/plugins/filter:/home/redacted/kvk/vault/ansible/roles/test/test/plugins/filter:/home/redacted/.ansible/plugins/filter:/usr/share/ansible/plugins/filter
ANSIBLE_FORCE_COLOR: '1'
ANSIBLE_LIBRARY: /home/redacted/kvk/vault/ansible/roles/test/venv/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/home/redacted/.cache/molecule/test/default/library:/home/redacted/kvk/vault/ansible/roles/test/test/library:/home/redacted/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
ANSIBLE_ROLES_PATH: /home/redacted/.cache/molecule/test/default/roles:/home/redacted/kvk/vault/ansible/roles/test:/home/redacted/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/redacted/.cache/ansible-lint/4165d8/roles

DEBUG: MOLECULE ENVIRONMENT:
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: delegated
MOLECULE_ENV_FILE: /home/redacted/kvk/vault/ansible/roles/test/test/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/redacted/.cache/molecule/test/default
MOLECULE_FILE: /home/redacted/.cache/molecule/test/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/redacted/.cache/molecule/test/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/redacted/.cache/molecule/test/default/inventory/ansible_inventory.yml
MOLECULE_PROJECT_DIRECTORY: /home/redacted/kvk/vault/ansible/roles/test/test
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/redacted/kvk/vault/ansible/roles/test/test/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/redacted/.cache/molecule/test/default/state.yml
MOLECULE_VERIFIER_NAME: ansible
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/tests

DEBUG: SHELL REPLAY:
ANSIBLE_COLLECTIONS_PATH=/home/redacted/.cache/molecule/test/default/collections:/home/redacted/.ansible/collections:/usr/share/ansible/collections:/etc/ansible/collections ANSIBLE_CONFIG=/home/redacted/.cache/molecule/test/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/home/redacted/kvk/vault/ansible/roles/test/venv/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/filter:/home/redacted/.cache/molecule/test/default/plugins/filter:/home/redacted/kvk/vault/ansible/roles/test/test/plugins/filter:/home/redacted/.ansible/plugins/filter:/usr/share/ansible/plugins/filter ANSIBLE_FORCE_COLOR=1 ANSIBLE_LIBRARY=/home/redacted/kvk/vault/ansible/roles/test/venv/lib/python3.8/site-packages/molecule/provisioner/ansible/plugins/modules:/home/redacted/.cache/molecule/test/default/library:/home/redacted/kvk/vault/ansible/roles/test/test/library:/home/redacted/.ansible/plugins/modules:/usr/share/ansible/plugins/modules ANSIBLE_ROLES_PATH=/home/redacted/.cache/molecule/test/default/roles:/home/redacted/kvk/vault/ansible/roles/test:/home/redacted/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/redacted/.cache/ansible-lint/4165d8/roles MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=delegated MOLECULE_ENV_FILE=/home/redacted/kvk/vault/ansible/roles/test/test/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/redacted/.cache/molecule/test/default MOLECULE_FILE=/home/redacted/.cache/molecule/test/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/redacted/.cache/molecule/test/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/redacted/.cache/molecule/test/default/inventory/ansible_inventory.yml MOLECULE_PROJECT_DIRECTORY=/home/redacted/kvk/vault/ansible/roles/test/test MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/redacted/kvk/vault/ansible/roles/test/test/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/redacted/.cache/molecule/test/default/state.yml MOLECULE_VERIFIER_NAME=ansible MOLECULE_VERIFIER_TEST_DIRECTORY=/home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/tests

COMMAND: ansible-playbook --diff --inventory /home/redacted/.cache/molecule/test/default/inventory --skip-tags molecule-notest,notest /home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/destroy.yml
INFO     Running default > syntax
# ... etcetera ...
```

The destroy stage is only an example. I pasted it here so I could truncate the rest. The behaviour is the same for all molecule stages (create, prepare, converge, idempotence, verify). Molecule is now unusable as a test framework, because I cannot see any errors from my role. For example, a failed task looks like this:

```
# ... etc
COMMAND: ansible-playbook --diff --inventory /home/redacted/.cache/molecule/test/default/inventory --skip-tags molecule-notest,notest /home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/converge.yml
CRITICAL Ansible return code was 4, command was: ['ansible-playbook', '--diff', '--inventory', '/home/redacted/.cache/molecule/test/default/inventory', '--skip-tags', 'molecule-notest,notest', '/home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/converge.yml']
WARNING  An error occurred during the test sequence action: 'converge'. Cleaning up.
INFO     Running default > cleanup
# ... etc
```

However, when I copy-paste the COMMAND, I **do** get ansible's output. Just to be clear: fixing the ansible error is not the point here. The point is that the whole error message is missing from molecule's output.

```
$ ansible-playbook --diff --inventory /home/redacted/.cache/molecule/test/default/inventory --skip-tags molecule-notest,notest /home/redacted/kvk/vault/ansible/roles/test/test/molecule/default/converge.yml

PLAY [Converge] *************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************
fatal: [instance]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname instance: Name or service not known", "unreachable": true}

PLAY RECAP ******************************************************************************************************************************************************************************************************************
instance                   : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

Am I missing something here?

**Comment by tadeboro** [comment] 2021-09-07 15:37
Duplicate of https://github.com/ansible-community/molecule/issues/3232

**Closed by tadeboro** 2021-09-07 15:37 UTC
Labels: bug
