### ISSUE TITLE
Molecule need to log the same way ansible does

### ISSUE THREAD

**Issue by rockandska** [ansible-community/molecule#1803] opened 2019-03-05 15:26 UTC
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible --version && molecule --version
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

It could sound as a joke, but molecule need to have the same bugs as ansible.
Why we need this ?
For example i spend some time to write an ansible role for [influxdb](https://github.com/rockandska/ansible-role-influxdb)
Since the module influxdb_user in the ansible core doesn't behave as I want, i decided to include a custom module in my role and use molecule for every role i write.
All went well, my custom module works and is taking over the core module and molecule return OK
My CI report a [success](https://travis-ci.com/rockandska/ansible-role-influxdb/builds/103072916) too

Now my role seems ok, i include it in a playbook and run it and........
```
TASK [influxdb : [InfluxDB] Create users] ******************************************************************************************************************************************************************
failed: [canoctl_influxdb1] (item={u'user_password': u'[redacted]', u'grants': [{u'privilege': u'ALL', u'database': u'[redacted]'}], u'user_name': u'[redacted]'}) => {"changed": false, "item": {"grants": [{"database": "[redacted]", "privilege": "ALL"}], "user_name": "[redacted]", "user_password": "[redacted]"}, "msg": "Unsupported parameters for (influxdb_user) module: grants Supported parameters include: ********, hostname, password, port, proxies, retries, ssl, state, timeout, udp_port, use_udp, user_name, user_password, username, validate_certs"}
```

It wasn't clear at first why it doesn't works and banging my head a few hours before finding this issue #ansible/ansible/issues/17078

The reason of this bug is obscure and the issue is old but it is clear that molecule use some configuration who allow in his way to bypass this bug.

You will find at least 2 examples in the issue, one is a [minimal example](https://gist.github.com/rockandska/a5a9bf4d5b07481cb66af2058bf4ae86) of my use case ( creation of docker_containers, then apply my role on them ) who cause the error above but works smoothly on my molecule scenario.

Hope you will find some solution to stick close to the ansible bugs to not let your users believe their roles are ok and publish them on ansible galaxy without them noticing than they are buggy :p

Best regards,

**Comment by decentral1se** [comment] 2019-03-05 18:44
> The reason of this bug is obscure and the issue is old but it is clear that molecule use some configuration who allow in his way to bypass this bug.

Hi, could you please explain your understanding of the reason of this bug? If I start to read through that age old 20+ comment issue, I might end up in the wrong place as you. Thanks.

**Comment by rockandska** [comment] 2019-03-05 19:04
From a discussion with @agaffney on IRC, he think that molecule use an alternate ansible.cfg who add some path to "library" and is the reason for why molecule doesn't hit this bug.
On Ansible side, I didn't dig in the source code to fully understanding it, but from the issue, it seems that this error is triggered when a core module (even if not related with the custom one) was used with "name" arg before the custom one but is not always the case.
NB: this error only happen when the custom module have the same name as the core module.
In my example, the module "add_host" use an arg "name" but doesn't trigger the error when the use of "docker_container" (who have a "name" arg) trigger the error.
In @alikins [repro example](https://github.com/alikins/ansible-bug-repro/blob/master/role_custom_module_override_17078) it seems that is the "name" of the task who trigger the error since "debug" doesn't have an arg.

So pragmatically, the reasons who seems to trigger the error don't seem to be related to an ansible.cfg configuration from my point of view, but despite that, it is clear that my role works fine with molecule (with last 2.5,2.6,,2.7) when it didn't work when using directly with a bare ansible without specific path configuration. (tested with last 2.5, 2.6, 2.7)

**Comment by rockandska** [comment] 2019-03-06 09:55
@decentral1se , you will find [here](https://github.com/rockandska/repro-issues/tree/master/molecule/molecule/issue_1803) a reproducible test case who show no errors with molecule but throw one in a similar case without molecule.

test-ko.yml playbook:

- first play (localhost)
  - create a docker container (molecule does it too in similar way)
  - add it to the inventory
- second play (localhost)
  - use the role test
    - debug msg
    - use of the custom module
    - debug msg

```
$ ansible-playbook --version
ansible-playbook 2.7.8
$ ansible-playbook -i localhost, test-ko.yml | grep -A 40 "roles/test"
TASK [roles/test : debug] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "In tasks/main.yml in test role"
}

TASK [roles/test : Test custom lib] ************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (influxdb_user) module: yourName Supported parameters include: admin, hostname, password, port, proxies, retries, ssl, state, timeout, udp_port, use_udp, user_name, user_password, username, validate_certs"}
	to retry, use: --limit @/home/ypanier/Documents/Git/repro-issues/molecule/molecule/issue_1803/test-ko.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=1   
```

test-ok.yml playbook: (just removed the creation of the container)

- first play (localhost)
  - add container to the inventory
- second play (localhost)
  - use the role test
    - debug msg
    - use of the custom module
    - debug msg
```
$ ansible-playbook -i localhost, test-ok.yml | grep -A 40 "roles/test"
TASK [roles/test : debug] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "In tasks/main.yml in test role"
}

TASK [roles/test : Test custom lib] ************************************************************************************************************************************************************************
ok: [localhost]

TASK [roles/test : debug] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "atest": {
        "changed": false, 
        "failed": false, 
        "msg": "Hello Test"
    }
}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0   
```

Test with molecule is ok with different version of ansible
```
$  tox | grep -Eo "ansible==.\..\...|\s+molecule-issue-1803.*ok=.*changed.*|py27-ansible..: commands succeeded"
ansible==2.5.15
    molecule-issue-1803        : ok=4    changed=0    unreachable=0    failed=0
ansible==2.6.14
    molecule-issue-1803        : ok=4    changed=0    unreachable=0    failed=0
ansible==2.7.8,
    molecule-issue-1803        : ok=4    changed=0    unreachable=0    failed=0
py27-ansible25: commands succeeded
py27-ansible26: commands succeeded
py27-ansible27: commands succeeded
```

**Comment by rockandska** [comment] 2019-03-07 16:49
Answer from @bcoca regarding this issue [here](https://github.com/ansible/ansible/issues/17078#issuecomment-470596284)
He also pushed this [PR](https://github.com/ansible/ansible/pull/53413) who seems to fix the issue observed on ansible side.

Maybe molecule project members could have a discussion with ansible maintainers about modifications done internally in molecule to see if another modifications could potentially have side effects as this case :smiley: 

Regards,

**Comment by ssbarnea** [comment] 2020-02-01 18:40
I will close this because logging is controlled by the molecule.yml file, which isolates it from user specific config, making its outcomes predictable. It is a feature, not a bug.

**Closed by ssbarnea** 2020-02-01 18:40 UTC
Labels: enhancement, wontfix

**Comment by rockandska** [comment] 2020-02-03 08:46
This issue was not about problem with logging... but the fact that molecule doesn't behave the same way that ansible and let user think that their role works (since it works with molecule) when it does not works when you running it only with ansible.

Quote from https://github.com/ansible/ansible/issues/17078
> @rockandska i don't know that molecule checks for 'over caching' in the internal engine
