### ISSUE TITLE
[FeatureRequest] Allow --limit with all molecule actions

### ISSUE THREAD

**Issue by rockandska** [ansible-community/molecule#1665] opened 2019-01-15 09:36 UTC
# Issue Type

- Feature request

# Molecule and Ansible details

```
ansible 2.5.5
molecule, version 2.19.0

```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

As asked by other people in #1471 , #1122, #827 , I think that molecule need to be able to filter the platforms on which the the tests are launched, based on what is provided into `platforms` key inside `molecule.yml`.

We indeed need to test multi-platform, but sometimes, when you know that the problem is only on one platform, need to only test this one before re-run the tests on all platforms.

As state in a comment by @retr0h , `converge` can already have this kind of comportment by specify  `molecule converge -- --limit instance-1` but it seems it not works with other options as :  
- check
- create
- destroy
- idempotence
- list
- login
- prepare
- side-effect
- test
- verify

In general, having the possibility to specify provisioner options on the command line regardless the action will be the best.

This kind of behaviour was asked multiple times and will be really handy for people who works with molecule and don't get why it was closed every time it was asked.

Could you please reconsidering the addition of this feature ?

Thanks,
Best regards,

**Comment by ssbarnea** [comment] 2019-01-15 18:53
I was expecting to have a parameter like -p|--platform that would allow to limit on which platforms to run the current scenario. Still, i was not able to spot this yet.

**Comment by rockandska** [comment] 2019-01-15 19:22
Glad to hear it :smile: , but it will limit the options to pass to the provisioner and the users will not have access to other options as --tags etc.. and in case molecule add a new provisioner in the future, it will require to have many options, and some not available to all provisioners.

But having provisioner options pass to all command through 'molecule [command] -- [provisioner-options] ...' could be maybe simpler to implement and will allow to not be stick to actual / future options of the provider ?

**Comment by lwm** [comment] 2019-01-15 20:59
> This kind of behaviour was asked multiple times and will be really handy for people who works with molecule and don't get why it was closed every time it was asked.

I believe it was a question of resources and feature scope for previous maintainers. Now that this project is under Ansible proper, we should have more of both :) Thanks for raising this issue, looks useful to me.

**Comment by rgarrigue** [comment] 2019-02-26 13:31
For consistency's sake, I'll add there's this `--host` in  `login` command, for example `molecule login --host molecule-common-debian9-systemd` that should be merged 

As ssbarnea said, I'ld expect a `-p|--platform` (or --limit)  on every command allowing to further refine the already existing `--scenario`.

**Comment by TomaszKlosinski** [comment] 2019-03-22 11:51
Is it possible to limit just verify (testinfra)? I'm testing an haproxy role with some dummy prometheus and jenkins containers (to test the load balancing). Now, I'd like to run my testinfra verification script against haproxy containers but not the dummy prometheus and jenkins ones. How can I do that?

**Comment by beenje** [comment] 2019-03-22 12:41
@TomaszKlosinski, with testinfra it's easy to limit the tests to a specific group or node.
The `get_hosts` method takes a group name or hostname in parameter:
```
testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('<host or group>')
```

**Comment by TomaszKlosinski** [comment] 2019-03-22 12:43
Thanks for the help.

**Comment by ssbarnea** [comment] 2019-03-22 14:02
If someone takes time to create a PR on this, I will be the first to review and help merging it. I was planning to add it myself but it seems that I do have a long queue of things that are more pressing than this.

**Comment by danielhoherd** [comment] 2019-04-09 22:52
I'm happy to see this discussion continuing from past closed tickets. My use case for having a `--platform` flag is that I want to be able to run the exact same tests (ie: the same scenario) on many platforms, but I want the ability to spawn parallel CI jobs for this. Without the ability to target a single platform found in molecule.yml, I have to resort to creating new scenarios, which causes duplicate code and violates DRY.

**Comment by ssbarnea** [comment] 2019-07-24 10:01
Did anyone made any efforths towards addressing this feature request? I am asking the pressure to implement it becomes bigger and bigger. As stated before the creating multiple scenarios does not scale. Also using a single overridable platform cripples the UX by preventing the users from running all plaforms.

**Comment by rshad** [comment] 2019-08-23 11:28
Hi all!

I found a temporary solution till `Molecule` get this feature added.

My idea it's based on modifying `molecule.yml` file each time we want to run `molecule test` with a specified image or platform. In my case, I have a similar configuration for each platform but the name and the image values differ from one to another.

For example, imagine I have the following configuration:
```
platforms:
  - name: platform_name
    image: image_name
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
    privileged: true
    memory_reservation: 2048m
```

My `script` first print a list of available images, and request from the user to select an image

```
images=( "solita/ubuntu-systemd:bionic" "solita/ubuntu-systemd:xenial" "milcom/centos7-systemd" "ubuntu:trusty" "centos:6" )

echo "Please select an image. "

select IMAGE in "${images[@]}";
do
     echo "You picked $IMAGE ($REPLY)"
     break
done

```

**Terminal Output**
```
vagrant@ansible:~/wazuh-ansible$ ./run_cluster_mode.sh
Please select an image.
1) solita/ubuntu-systemd:bionic  4) ubuntu:trusty
2) solita/ubuntu-systemd:xenial  5) centos:6
3) milcom/centos7-systemd
```

I also have an array with each platform name I want to associate to each image
```
platform=( "bionic" "xenial" "centos7" "trusty" "centos6" )
```

Once the image is selected then using `sed` I replace both variables `name` and `image` in `molecule.yml`, taking into account that we should have a backup of `molecule.yml`, in my case it's called `molecule.yml.template`
``` 
index=$(($REPLY - 1))

cp "molecule.yml.template" "molecule.yml"

sed -i "s|image_name|${images[$index]}|g" "$i/molecule.yml"
sed -i "s/platform_name/${platform[$index]}/g" "$i/molecule.yml" 
```

Once my `moldecule.yml` is prepared, then I run my `Molecule` test:
```
molecule test --destroy=never
```

Or if you're working with `Pipefile`, then
```
pipenv run test
```

Where my `Pipfile` looks like
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
docker-py = "*"
ansible = "==2.7.13"
molecule = "==2.20.2"

[dev-packages]

[requires]
python_version = "2.7"

[scripts]
test ="molecule test --destroy=never"
```


Please find the complete script [Here!](https://github.com/wazuh/wazuh-ansible/blob/3.10_7.3.0_issue_220/run_cluster_mode.sh) . This script was designed for `Wazuh` cluster mode testing.

Hope it would help :)

Kind regards,

Rshad

**Comment by rshad** [comment] 2019-08-23 14:36
@ssbarnea I'll try to dedicate a time to get this feature added in Molecule.

**Comment by zhan9san** [comment] 2022-04-19 15:11
Hi @rockandska 

Thanks for your patience.

I noticed #3416 has been merged into main branch.

Could you please confirm whether address this issue?
If yes, could you close this issue?

**Comment by danielhoherd** [comment] 2022-04-19 17:57
I just tested this on 3.6.2.dev37 and it worked as described. 3.6.1 does not work due to missing the `--scenario-name` flag. As expected, I was able to reduce a lot of duplication with this change, even on a small ansible role: "18 files changed, 6 insertions(+), 186 deletions(-)" This is a very welcome change. Thanks @zhan9san for putting in the work!

**Comment by zhan9san** [comment] 2022-06-17 09:51
This issue is fixed in latest version.

```shell
pip install -U molecule
```

Doc: https://molecule.readthedocs.io/en/latest/getting-started.html#run-a-full-test-sequence

**Closed by zhan9san** 2022-06-17 09:51 UTC
Labels: enhancement, help wanted

**Comment by ep4sh** [comment] 2024-06-06 08:55
Hi team, 
we developed a huge automation with molecule, including a large amount of platforms (docker containers), but often we need to apply a single run with a specific platform. 
I found that it's impossible with current version, but recently this feature was available.
Are there any plans to include it?

**Comment by danielhoherd** [comment] 2024-06-06 14:00
@ep4sh this feature has been available for 2 years.

https://github.com/danielhoherd/ansible-role-exiftool/blob/main/Makefile#L28
