### ISSUE TITLE
Molecule loads group_vars files in alphabetical order

### ISSUE THREAD

**Issue by glennie** [ansible-community/molecule#1784] opened 2019-02-27 17:02 UTC
# Issue Type
# Molecule and Ansible details

```
ansible --version && molecule --version

--> ansible 2.7.5
  config file = None
  configured module search path = [u'/home/glennie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/glennie/.virtualenv/molecule-cf9b8409524124e12fc5da69255c535d/local/lib/python2.7/site-packages/ansible
  executable location = /home/glennie/.virtualenv/molecule-cf9b8409524124e12fc5da69255c535d/bin/ansible
  python version = 2.7.15 (default, Jul 28 2018, 11:29:29) [GCC 8.1.0]


--> molecule, version 2.18.1
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:

# Desired Behavior

Hello,

Molecule injects configuration from group_vars in alphabetical order. It should load those files ordered by their apparence in groups key (from molecule.yml).

Follows an excerpt from my molecule.yml file:

```yaml
platforms:
    - `name: testhost                                                                   
      groups:
        - bo
        - production
        - ci
```
As you can see, I've 3 groups. In my group_vars diretory, I've 3 files matching 3  this groups.

Some variables from production should be overridden by the ci group. But, there are not. I allways have values from production file.

On the other hand, groups are written as:

```yaml
groups:
        - bo                                                                                                                                           
        - production
        - zzzz_ci
```

and the group_vars/ci is renamed to group_vars/zzzz_ci, the variables are properly overridden.

# Actual Behaviour

As stated above, molecule should load group_vars as they are written en molecule.yml

Kind regards,

PS: Thanks for this piece useful and open source software.

**Comment by decentral1se** [comment] 2019-03-03 20:10
Hi @glennie, thanks for this report. Unfortunately, I'm having a hard time understanding this issue and the cause of it. Could you provide a simple reproducible example? That'd be great. Otherwise, I hope someone else can weigh in on this!

**Comment by ssbarnea** [comment] 2020-07-19 10:22
Closing as I doubt anyone will do anything about this. Still, if that is important for you, feel free to make a PR that changes this current behavior.

**Closed by ssbarnea** 2020-07-19 10:22 UTC
