### ISSUE TITLE
molecule init: Error: Invalid value for '--driver-name' / '-d': 'docker' is not 'delegated'

### ISSUE THREAD

**Issue by cupen** [ansible-community/molecule#3287] opened 2021-11-03 08:08 UTC
From here.
https://molecule.readthedocs.io/en/latest/getting-started.html#molecule-scenarios

# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version && molecule --version
ansible --version && molecule --version
ansible 2.10.9
  config file = /home/cupen/.ansible.cfg
  configured module search path = ['/home/cupen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cupen/.local/lib/python3.9/site-packages/ansible
  executable location = /home/cupen/.local/bin/ansible
  python version = 3.9.7 (default, Oct 10 2021, 15:13:22) [GCC 11.1.0]
molecule 3.5.2 using python 3.9 
    ansible:2.10.9
    delegated:3.5.2 from molecule

```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

Detail any linters or test runners used:

# Desired Behavior
`molecule init scenario --driver-name docker` works

# Actual Behaviour
```
$ molecule init scenario --driver-name docker
Usage: molecule init scenario [OPTIONS] [SCENARIO_NAME]
Try 'molecule init scenario --help' for help.

Error: Invalid value for '--driver-name' / '-d': 'docker' is not 'delegated'.
```

**Comment by tadeboro** [comment] 2021-11-03 09:06
Duplicate of https://github.com/ansible-community/molecule/issues/3259

**Closed by tadeboro** 2021-11-03 09:06 UTC
Labels: bug
