### ISSUE TITLE
molecule login broken since 3.6.0

### ISSUE THREAD

**Issue by udondan** [ansible-community/molecule#3462] opened 2022-03-08 12:12 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```bash
# molecule --version
molecule 3.6.1 using python 3.7 
    ansible:2.9.13
    delegated:3.6.1 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
    ec2:0.4 from molecule_ec2
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When running `molecule login` it should work

# Actual Behaviour

Sine Molecule 3.6.0 it doesn't. 

```bash
# molecule login -h foo
INFO     Running default > login
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/login.py", line 166, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 149, in execute_subcommand
    return command(config).execute()
  File "/usr/local/lib/python3.7/site-packages/molecule/logger.py", line 188, in wrapper
    rt = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/login.py", line 101, in execute
    self._get_login(hostname)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/login.py", line 146, in _get_login
    app.runtime.exec(cmd)
  File "/usr/local/lib/python3.7/site-packages/ansible_compat/runtime.py", line 145, in exec
    cwd=cwd,
  File "/usr/lib64/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/env ssh 1.2.3.4 -l ec2-user -p 22 -i /molecule-cache/ssh_key -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no': '/usr/bin/env ssh 1.2.3.4 -l ec2-user -p 22 -i /molecule-cache/ssh_key -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'
```
Apparently it checks for the command to be present as file.

I verified this works until 3.5.2 and is broken in 3.6.0 and 3.6.1. Looking at the changelog, my best guess is this is caused by #3237

**Comment by amarao** [comment] 2022-03-16 09:30
Duplicate of #3435

**Comment by ziegenberg** [comment] 2022-04-11 20:23
This should be fixed by #3468.

**Closed by ziegenberg** 2022-04-11 20:23 UTC
Labels: bug

**Comment by kbreit** [comment] 2022-06-01 01:43
Is there supposed to be a release soon which will fix this bug?

**Comment by amine7777** [comment] 2022-10-08 10:36
@kbreit 

For my side Molecule couldn't find the file **instance_config.yml** in the cache. I have used this and restarted the container and now I could run `molecule login `

`driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker`
      
Hope this will help you
