### ISSUE TITLE
Molecule driver dependencies (collections) is not installed to the correct place

### ISSUE THREAD

**Issue by klj613** [ansible-community/molecule#3266] opened 2021-10-08 17:36 UTC
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version

ansible [core 2.11.5] 
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/workspace/code/molecule/projectdir/.tox/rolename/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/workspace/code/molecule/projectdir/.tox/rolename/bin/ansible
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
  jinja version = 3.0.2
  libyaml = True
molecule 3.4.1 using python 3.9 
    ansible:2.11.5
    delegated:3.4.1 from molecule
    docker:1.0.2 from molecule_docker requiring collections: community.docker>=1.8.0
    ec2:0.3 from molecule_ec2
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

When "dependency" is enabled I would expect any collections installed for the driver itself (e.g. the docker driver) to be installed to ${MOLECULE_EPHEMERAL_DIRECTORY}/collections

"Driver" collections: https://github.com/ansible-community/molecule-docker/commit/b7cdeff28a6eab463d112b614986db6655aa1d06 which is picked up by https://github.com/ansible-community/molecule/blob/main/src/molecule/dependency/base.py#L91

# Actual Behaviour

Have tried both the shell and galaxy methods however the collection installed as a dependency of the "docker" driver is installed to ~/.ansible/collections/ansible_collections instead of ${MOLECULE_EPHEMERAL_DIRECTORY}/collections (this is primarily an issue when running multiple molecule commands concurrently via tox)

Disabling the "dependency" step works as this is checked before calling `super().execute()` for both shell and galaxy, e.g: https://github.com/ansible-community/molecule/blob/main/src/molecule/dependency/shell.py#L92

**Comment by konstruktoid** [comment] 2021-12-30 17:27
I believe I trigger this when running on the development version of Ansible, but not version 4 or 5.

```sh
$ ansible --version && molecule --version
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can
become unstable at any point.
ansible [core 2.13.0.dev0]
  config file = None
 [...]/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
 [...]/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.9 (main, Nov 21 2021, 03:23:44) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
molecule 3.5.3.dev43 using python 3.9
    ansible:2.13.0.dev0
    delegated:3.5.3.dev43 from molecule
    podman:1.0.1 from molecule_podman requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:1.0.0 from molecule_vagrant
```

`tox.ini` (https://github.com/konstruktoid/ansible-docker-rootless/blob/main/tox.ini):
```sh
$ cat tox.ini
[tox]
minversion = 3.20
envlist =
  py39-ansible{4,5,devel}
  py310-ansible{4,5,devel}
skipsdist = true

[testenv]
passenv = *
deps =
    ansible4: ansible==4.10
    ansible5: ansible==5.1.0
    ansibledevel: https://github.com/ansible/ansible/archive/devel.tar.gz
    ansible-lint
    docker
    molecule
    molecule-vagrant
commands =
    molecule test
```

`molecule/default/verify.yml:98` is https://github.com/konstruktoid/ansible-docker-rootless/blob/main/molecule/default/verify.yml#L98-L116.

`tox` results:
```sh
  py39-ansible4: commands succeeded
  py39-ansible5: commands succeeded
ERROR:   py39-ansibledevel: commands failed
  py310-ansible4: commands succeeded
  py310-ansible5: commands succeeded
ERROR:   py310-ansibledevel: commands failed
```

```
$ tox -e py39-ansibledevel
py39-ansibledevel installed: ansible-compat==0.5.0,ansible-core @ https://github.com/ansible/ansible/archive/devel.tar.gz,ansible-lint==5.3.1,arrow==1.2.1,bcrypt==3.2.0,binaryornot==0.4.4,bracex==2.2.1,Cerberus==1.3.2,certifi==2021.10.8,cffi==1.15.0,chardet==4.0.0,charset-normalizer==2.0.9,click==8.0.3,click-help-colors==0.9.1,colorama==0.4.4,commonmark==0.9.1,cookiecutter==1.7.3,cryptography==36.0.1,distro==1.6.0,docker==5.0.3,enrich==1.2.6,idna==3.3,Jinja2==3.0.3,jinja2-time==0.2.0,MarkupSafe==2.0.1,molecule==3.5.2,molecule-vagrant==1.0.0,packaging==21.3,paramiko==2.9.1,pluggy==1.0.0,poyo==0.5.0,pycparser==2.21,Pygments==2.11.0,PyNaCl==1.4.0,pyparsing==3.0.6,python-dateutil==2.8.2,python-slugify==5.0.2,python-vagrant==0.5.15,PyYAML==5.4.1,requests==2.26.0,resolvelib==0.5.4,rich==10.16.1,ruamel.yaml==0.17.19,ruamel.yaml.clib==0.2.6,selinux==0.2.1,six==1.16.0,subprocess-tee==0.3.5,tenacity==8.0.1,text-unidecode==1.3,urllib3==1.26.7,wcmatch==8.3,websocket-client==1.2.3
py39-ansibledevel run-test-pre: PYTHONHASHSEED='1268733304'
py39-ansibledevel run-test: commands[0] | molecule test
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
INFO     default scenario test matrix: dependency, lint, cleanup, destroy, syntax, create, prepare, converge, idempotence, side_effect, verify, cleanup, destroy
INFO     Performing prerun...
INFO [...]/.ansible/plugins/modules:/usr/share/ansible/plugins/modules
INFO [...]/.ansible/collections:/usr/share/ansible/collections
INFO [...]/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
INFO [...]/.ansible/roles/konstruktoid.docker_rootless symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > lint
COMMAND: set -e
ansible-lint --exclude .git --exclude .github --exclude tests/
yamllint -d '{"extends":"default","ignore":".tox*\n.git*","rules":{"line-length":{"max":120,"level":"warning"}}}' .

[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
WARNING  Listing 1 violation(s) that are fatal
syntax-check: couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.
molecule/default/verify.yml:98:11 [WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.

The [...]/Git/ansible-docker-rootless/molecule/default/verify.yml': line 98, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


        - name: start rootful nginx container
          ^ here



Finished with 1 failure(s), 0 warning(s) on 28 files.
CRITICAL Lint failed with error code 2
WARNING  An error occurred during the test sequence action: 'lint'. Cleaning up.
INFO     Running default > cleanup
WARNING  Skipping, cleanup playbook not configured.
INFO     Running default > destroy
[WARNING]: You are running the development version of Ansible. You should only
run Ansible from "devel" if you are modifying the Ansible engine, or trying out
features under development. This is a rapidly changing source of code and can
become unstable at any point.
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names
to new standard, use callbacks_enabled instead. This feature will be removed
from ansible-core in version 2.15. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Skipping callback plugin 'profile_tasks', unable to load

PLAY [Destroy] *****************************************************************

TASK [Destroy molecule instance(s)] ********************************************
ok: [localhost]

TASK [Populate instance config] ************************************************
ok: [localhost]

TASK [Dump instance config] ****************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

INFO     Pruning extra files from scenario ephemeral directory
ERROR: [...]/Git/ansible-docker-rootless/.tox/py39-ansibledevel/bin/molecule test (exited with code 1)
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
ERROR:   py39-ansibledevel: commands failed
```

**Comment by zhan9san** [comment] 2022-04-21 09:24
@konstruktoid 

> ERROR! couldn't resolve module/action 'docker_container'. This often indicates a misspelling, missing collection, or incorrect module path.

I think this issue is not related to `molecule` but `ansible-devel`

The non-devel ansible is installed, and `ansible_collection` `community.docker` will be installed as well.

##### How to reproduce

1. Non-devel Ansible

  ```shell
  $ python3 -m venv venv
  $ source venv/bin/activate
  $ pip install ansible
  $ ls venv/lib/python3.9/site-packages/ansible_collections/community/docker
  CHANGELOG.rst COPYING       FILES.json    MANIFEST.json README.md     changelogs    docs          meta          plugins       tests
  ```

2. devel Ansible

No `ansible_collection` is installed

  ```shell
  $ python3 -m venv venv
  $ source venv/bin/activate
  $ pip install git+https://github.com/ansible/ansible.git@devel
  $ ls -d  venv/lib/python3.9/site-packages/ansible*
  venv/lib/python3.9/site-packages/ansible                            venv/lib/python3.9/site-packages/ansible_core-2.14.0.dev0.dist-info venv/lib/python3.9/site-packages/ansible_test
  ```

**Comment by ssbarnea** [comment] 2022-06-01 10:11
Please try https://github.com/ansible-community/molecule/discussions/3569 and keep in mind that we do not install dependencies in default locations by design, as we want to isolate testing environment from user one, avoiding cross contaminations.

**Closed by ssbarnea** 2022-06-01 10:11 UTC
Labels: bug
